version: '3.8'

services:
  build_gst:
    build:
       context: .
       dockerfile: Dockerfile 
    
    shm_size: '1gb'
    image: gstreamer_1.26_lcvec_beta_2
    container_name: gstreamer_2
    ipc: "host"
    privileged: true
    network_mode: "host"
    
    # Modern GPU support for Docker Compose 3.8+
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
    
    restart: on-failure
    #command: ["/bin/bash","-c","sleep 36000"]
    #entrypoint: ["/bin/sh", "/test_h264.sh"]
    entrypoint: ["/bin/sh", "/test_shaka.sh"]

    
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=:0
      - XAUTHORITY=/tmp/.docker.xauth
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    
    volumes:
      - ./test_shaka.sh:/test_shaka.sh:ro
      - ./test_h264.sh:/test_h264.sh:ro
      - /sys:/sys
      - $HOME/.Xauthority:/root/.Xauthority
      - /run/dbus/system_bus_socket:/host/run/dbus/system_bus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /dev/shm:/dev/shm:rw

  shaka:
    image: google/shaka-packager:latest
    container_name: shaka
    entrypoint: ["/bin/sh", "/packager2.sh"]
    network_mode: "host"
    depends_on:
      - gst-worker_2

    environment:
      - UDP_PORT=10000
      - SEGMENT_DURATION=4
      - DASH_MANIFEST=manifest.mpd
      - HLS_MASTER=master.m3u8
    volumes:
      - ./packager.sh:/packager.sh:ro
      - ./packager2.sh:/packager2.sh:ro
      - ./output:/output

  gst-worker_2:
    image: gstreamer_1.26_lcvec_beta_2
    restart: on-failure
    ipc: "host"
    privileged: true
    network_mode: "host"
    
    # GPU support for worker service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
     
    environment:
      - DISPLAY=:0
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    
    shm_size: '1gb'
 
    healthcheck:
      test: ["CMD", "gst-inspect-1.0", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5
        
    depends_on:
      - build_gst
    
    volumes:
      - /sys:/sys
      - $HOME/.Xauthority:/root/.Xauthority
      - /run/dbus/system_bus_socket:/host/run/dbus/system_bus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
 
    
  
